### ISSUE TITLE
SWT loadout review and rework

### ISSUE THREAD

**Issue by DarkMessiah27** [DarkMessiah27/2.PzD-Mission-Template#101]
Fritz has requested that each SWT team be given at least one rifle as having a dual SMG setup really limits their effectiveness at longer range.

To do:

- [x] Check each SWT team and see if they have two SMG's. If so, make the following change: give the gunner a rifle unless they require their main weapon slot for the SWT equipment. For example, an HMG gunner needs his primary weapon slot for the HMG, hence the rifle will be given to the TL. On the other hand, a Bazooka gunner does not need his primary weapon for his SWT equipment, and can therefore be given the rifle.
- [x] #112

**Comment by HeinrichFalk** [comment]
I think we should split off SWT supplies in the vehicle loadouts. With the current system we have a overflow of unused SWT equipment and it can also be smart if we want to create a vehicle loadout for them in the future (if they get a SWT vehicle) so they have their supplies with them instead of spread over 3-4 halftracks.
